// Notes with claim-type badges. The FACT / ARGUMENT / OPINION / AI distinction
// matters most when you are reading your own note back under pressure and need
// to know instantly whether you can assert it.

import { useEffect, useMemo, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { api } from '../lib/api'
import { useApp } from '../lib/store'
import { Panel, Empty, Badge, Spinner, CopyButton, CountryOptions } from '../components/ui'

const BADGES = ['FACT', 'ARGUMENT', 'OPINION', 'AI'] as const

const BADGE_HELP: Record<string, string> = {
  FACT: 'Supported by a source you can point to',
  ARGUMENT: 'A strategic interpretation, not a fact',
  OPINION: 'Your chosen position',
  AI: 'Generated by the model — verify before asserting',
}

export function Notes() {
  const [params] = useSearchParams()
  const { session, toast } = useApp()
  const [notes, setNotes] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [body, setBody] = useState('')
  const [badge, setBadge] = useState<typeof BADGES[number]>('FACT')
  const [country, setCountry] = useState('')
  const [filter, setFilter] = useState('')
  const [filterBadge, setFilterBadge] = useState('')
  const inputRef = useRef<HTMLTextAreaElement>(null)

  const load = () => { api.notes().then(setNotes).catch(() => {}).finally(() => setLoading(false)) }
  useEffect(load, [])
  useEffect(() => { if (params.get('new')) inputRef.current?.focus() }, [params])

  const add = async () => {
    const text = body.trim()
    if (!text) return
    setBody('')
    const created = await api.post<any>('/api/notes', {
      body: text, badge, country: country || null, session_id: session?.id ?? null,
    }).catch(() => null)
    if (created) { setNotes((n) => [created, ...n]); toast('Note saved', 'good') }
    else toast('Could not save note', 'bad')
  }

  const patch = async (n: any, p: Record<string, unknown>) => {
    setNotes((prev) => prev.map((x) => (x.id === n.id ? { ...x, ...p } : x)))
    await api.patch(`/api/notes/${n.id}`, p).catch(() => {})
  }

  const remove = async (n: any) => {
    setNotes((prev) => prev.filter((x) => x.id !== n.id))
    await api.del(`/api/notes/${n.id}`).catch(() => {})
  }

  const filtered = useMemo(() => {
    let list = notes
    if (filterBadge) list = list.filter((n) => n.badge === filterBadge)
    if (filter.trim()) {
      const needle = filter.toLowerCase()
      list = list.filter((n) => n.body.toLowerCase().includes(needle))
    }
    return list
  }, [notes, filter, filterBadge])

  const exportNotes = () => {
    const text = notes.map((n) =>
      `[${n.badge}]${n.country ? ` (${n.country})` : ''} ${new Date(n.created_at).toLocaleString()}\n${n.body}\n`
    ).join('\n')
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `mun-notes-${new Date().toISOString().slice(0, 10)}.txt`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  return (
    <div className="p-4 flex flex-col gap-3 h-full max-w-[900px]">
      <Panel title="New note">
        <div className="p-3 flex flex-col gap-2">
          <textarea ref={inputRef} className="textarea" rows={3} value={body}
            onChange={(e) => setBody(e.target.value)}
            onKeyDown={(e) => { if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) add() }}
            placeholder="What happened? Who said what? Ctrl+Enter to save." />
          <div className="flex items-center gap-2 flex-wrap">
            <div className="flex gap-1">
              {BADGES.map((b) => (
                <button key={b} className={`chip badge-${b}`} title={BADGE_HELP[b]}
                  style={{ opacity: badge === b ? 1 : 0.4, cursor: 'pointer' }}
                  onClick={() => setBadge(b)}>{b}</button>
              ))}
            </div>
            <select className="select max-w-[140px]" value={country} onChange={(e) => setCountry(e.target.value)}>
              <option value="">No country</option>
              <CountryOptions />
              <option value="OTHER">Other</option>
            </select>
            <div className="flex-1" />
            <button className="btn btn-primary" onClick={add} disabled={!body.trim()}>Save note</button>
          </div>
          <p className="text-[11px]" style={{ color: 'var(--faint)' }}>{BADGE_HELP[badge]}</p>
        </div>
      </Panel>

      <div className="flex items-center gap-2 shrink-0">
        <input className="input max-w-xs" placeholder="Filter notes…" value={filter}
          onChange={(e) => setFilter(e.target.value)} />
        <div className="flex gap-1">
          <button className="btn btn-sm" style={!filterBadge ? { borderColor: 'var(--color-signal)' } : {}}
            onClick={() => setFilterBadge('')}>All</button>
          {BADGES.map((b) => (
            <button key={b} className={`chip badge-${b}`} style={{ opacity: filterBadge === b ? 1 : 0.5, cursor: 'pointer' }}
              onClick={() => setFilterBadge(filterBadge === b ? '' : b)}>{b}</button>
          ))}
        </div>
        <div className="flex-1" />
        <span className="text-[11px]" style={{ color: 'var(--faint)' }}>{filtered.length} of {notes.length}</span>
        <button className="btn btn-sm" onClick={exportNotes} disabled={!notes.length}>Export</button>
      </div>

      <div className="flex-1 min-h-0 scroll-y flex flex-col gap-1.5">
        {loading ? <Spinner label="Loading notes…" />
          : filtered.length ? filtered.map((n) => (
            <div key={n.id} className="panel p-2.5 flex items-start gap-2.5">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-1.5 mb-1">
                  <Badge kind={n.badge} />
                  {n.country && <span className="chip">{n.country}</span>}
                  <span className="text-[11px]" style={{ color: 'var(--faint)' }}>
                    {new Date(n.created_at).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}
                  </span>
                </div>
                <p className="text-[13px] whitespace-pre-wrap leading-relaxed">{n.body}</p>
              </div>
              <div className="flex flex-col gap-1 shrink-0">
                <button className="btn btn-sm" onClick={() => patch(n, { pinned: !n.pinned })}
                  title="Pin to the quick-context panel">{n.pinned ? '★' : '☆'}</button>
                <CopyButton text={n.body} label="⧉" className="btn btn-sm" />
                <button className="btn btn-sm" onClick={() => remove(n)} title="Delete">✕</button>
              </div>
            </div>
          )) : <Empty icon="✎" title="No notes yet"
            hint="Notes taken during committee are exported with the session summary." />}
      </div>
    </div>
  )
}
